algoritmo "Atividade Prática 4"

var
num1: real
num2: real
num3: real
resultadoSoma: real
resultadoMedia: real

inicio
Escreval("Digite o primeiro número: ")
Leia(num1)
Escreval("Digite o segundo número: ")
Leia(num2)
Escreval("Digite o terceiro número: ")
Leia(num3)

resultadoSoma <- num1+num2+num3
resultadoMedia <- resultadoSoma/3

Escreval("Soma e média dos números são: ")
Escreval("Resultado da Soma: ", resultadoSoma)
Escreval("Resultado da Média", resultadoMedia)

fimalgoritmo